### ISSUE TITLE
control the toolchain

### ISSUE THREAD

**Issue by dakom** [Pauan/rollup-plugin-rust#1]
Is it possible to specify nightly/stable/etc?

**Comment by Pauan** [comment]
[(Wrong repo)](https://github.com/wasm-tool/rollup-plugin-rust#readme)

Yes, you can use `rustup override set nightly` to enable Nightly only on the current directory.

Or you can [create a `rust-toolchain` file](https://github.com/rust-lang/rustup#the-toolchain-file) in your project which contains the text `nightly`.
